# Generated by Django 5.1.3 on 2024-11-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
