# Generated by Django 5.1.3 on 2024-12-02 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productdetails_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='products_ca_name_693421_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetails',
            index=models.Index(fields=['name'], name='products_pr_name_6239a7_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetails',
            index=models.Index(fields=['creator'], name='products_pr_creator_297b06_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetails',
            index=models.Index(fields=['price'], name='products_pr_price_5dce53_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['name'], name='products_su_name_4ac726_idx'),
        ),
    ]
